### ISSUE TITLE
OnStaff warning when read only for new staff

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/pacific-emis-pdf-survey-builder#57]
When inserting new staff the onStaff field is read only. The logic behind it is that a new staff is automatically on staff. But the field then produces a warning which the user is unable to make disappear.

![Image](https://github.com/user-attachments/assets/239b11ed-c73e-45e0-bd63-7918c8ada576)

![Image](https://github.com/user-attachments/assets/d0431a16-9d0f-4342-8642-f798836ceea4)

**Comment by ghachey** [comment]
With the OnStaff blank the teacher is not load. This means all new staff are not loaded with this bug hence re-classified as blocker

**Comment by softwords** [comment]
Fix coming this morning - will require SQL update.

Some background: 
As we know, in previous surveys, a different layout was used for Expected Staff (prepopulated) and new Staff. This was reflected in the field naming ( and therefore in the exported xfdf) : Exptected Staff was under the node TL, and new staff under the node T.  Both nodes of xml were updated using [pTeacherWrite].[xfdfTeachers], some variations based on TL vs T are in that SP.
Now , only TL node is used for both expected Staff and new staff. Expected Staff is still prepopulated, now using the pdfSurvey/generate REST end point. Note that this populates the hidden field tID, unhides OnStaff, and locks the UI for all Expected Staff.
From there, the teacher block is unlocked if you select OnStaff = Y , and is locked (if not already locked) if you select OnStaff = N.
OnStaff must be not null for every expected teacher; ie every teacher where tID is not null. 

New staff are those where tID is null (the field is hidden, there is no way to provide a value for it through the UI). OnStaff is hidden and the teacher block is unlocked. If a value is entered for FamilyName , this is considered to be a new teacher, and the Verify Responses tests will be applied to this teacher. In the upload ([pTeacherWrite].[xfdfTeachers]) when tID is missing, it is searched for using name, Dob, gender.

**Comment by ghachey** [comment]
This is perfect. One last related thing here. In the event of teacher de-duplication which is happening more and more here, will the "change" in tID from the prepopulated surveys still throw an error? What is the best way to handle this? Create a new teacher with a warning that another de-duplication will be needed?

**Comment by softwords** [comment]
>> Create a new teacher with a warning that another de-duplication will be needed?

I think so. As the process goes along, the temporary data holds the tID for all the expected staff, and fills it in for New Staff if they are located in the teacher file ( by various combos of name, dob gender payroll no).

If at the end of that process we don't have any tID, we create a new TeacherIdentity record and use that. this may then be potentially deduped with some other record.

So I would propose that before createing the new TeacherIdenoty, we delete every existing tID (ie preopulated one) that is no longer found in TeacherIdentity. Then it will create a new TeacherIdentoty and you can dedup at your leisure.

Related is if the teacher is found, but is at a different school in the same year. Again I think we clear the tID, create a new TeacherIdentity and allow deduping to resolve the conflict.

**Comment by softwords** [comment]
Resolved by updates to [pTeacherWrite].[xfdfTeachers], pushed to waspinator.KEMIS. Also psurveyOps.xfdfLoadLocal

**Comment by ghachey** [comment]
@softwords please can you push this fix again with SQLDelta. The change was lost as we deleted and restored the test DB for testing with identical copy to production.

**Comment by softwords** [comment]
Done

**Comment by ghachey** [comment]
@softwords Still get the warning. Should a new staff raise a warning?

**Comment by softwords** [comment]
>> Should a new staff raise a warning?

No.

Can you send me the PDF ?

**Comment by ghachey** [comment]
This only happens on first time loading of a survey with new staff. Subsequent reload of same survey the warning disappears. Sent a PDF by email though you will need to load on your own machine as this PDF was already loaded in the test systme online and thus the warning will not show.

**Comment by softwords** [comment]
OnStaff warning fixed in xfdfTeachers,
lines 361 forward:

INSERT INTO @messages
Select 1, null, FamilyName + ', ' + FirstName + ' (' + convert(nvarchar(2), seq) + ') tID: ' +  convert(nvarchar(10), tID) +  ' OnStaff? is blank - expected teacher not added'
FROM @data
WHERE tID is not null		-- expected staff
and OnStaff is null
